In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [5]:
df['COMMISSION_PCT']=df['COMMISSION_PCT'].fillna(0.22)
df['MANAGER_ID']=df['MANAGER_ID'].fillna(100.0)
df['DEPARTMENT_ID']=df['DEPARTMENT_ID'].fillna(50.0)

In [7]:
df['MANAGER_ID']=df['MANAGER_ID'].astype(int)
df['DEPARTMENT_ID']=df['DEPARTMENT_ID'].astype(int)

In [9]:
df['HIRE_DATE']= pd.to_datetime(df['HIRE_DATE'])

In [ ]:
''' 
GROUPBY()
AGGREGRATE func()
  1. mean()
  2. max()
  3. min()
  4. count()
  5. sum()

'''

In [ ]:
#If you use groupby then aggregrate func must be used 
#If one uses aggregrate func then groupby clause is not mandatory

In [ ]:
#variable = df.groupby(column1)[column2].count()

In [ ]:
#variable = df.groupby(column1)

In [ ]:
#Find total employees working in each departemt

In [14]:
#For formatting use // reset_index()
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count().reset_index()
emp_dep

    DEPARTMENT_ID  EMPLOYEE_ID
0              10            1
1              20            2
2              30            6
3              40            2
4              50           46
5              60            5
6              70            2
7              80           34
8              90            3
9             100            6
10            110            4

In [ ]:
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count()

format_data = emp_dep.to_markdown(stralign='center', numalign= 'center')
print(format_data)