In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('Dataset/financial_loan_data.xlsx')
df.to_csv('Dataset/financial_loan_data.csv', index=False)

In [4]:
df = pd.read_csv('Dataset/financial_loan_data.csv')
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [5]:
df.isnull().sum()

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [6]:
df['emp_title'].fillna('None', inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_340\4232942754.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['emp_title'].fillna('None', inplace=True)

In [7]:
df['issue_date'] = pd.to_datetime(df['issue_date'])

In [8]:
df['month_num'] = df['issue_date'].dt.month
df['month_name'] = df['issue_date'].dt.month_name()

In [9]:
MTD_Month = 12
PMTD_Month = 11

In [10]:
def format_currency(val):
    return f'Rs.{val:,.2f}'


def format_pct(val):
    return f"{val * 100:,.2f}%" if val <= 1.0 else f"{val:,.2f}%"

# Total Loan Applications

In [11]:
Total_Loan_Applications = df['id'].count()
Total_MTD_Loan_Applications = df[df['month_num'] == MTD_Month]['id'].count()
Total_PMTD_Loan_Applications = df[df['month_num'] == PMTD_Month]['id'].count()
Total_Loan_Applications_MoM_Growth = round(((Total_MTD_Loan_Applications - Total_PMTD_Loan_Applications)/Total_PMTD_Loan_Applications)*100, 2)

In [12]:
print(f'Total Loan Applications: {Total_Loan_Applications}')
print(f'Total MTD Loan Applications: {Total_MTD_Loan_Applications}')
print(f'Total PMTD Loan Applications: {Total_PMTD_Loan_Applications}')
print(f'Total Loan Applications MoM Growth: {Total_Loan_Applications_MoM_Growth}')

Total Loan Applications: 38576
Total MTD Loan Applications: 4314
Total PMTD Loan Applications: 4035
Total Loan Applications MoM Growth: 6.91

# Total Funded Amount

In [13]:
Total_Funded_Amount = df['loan_amount'].sum()
Total_MTD_Funded_Amount = df[df['month_num'] == MTD_Month]['loan_amount'].sum()
Total_PMTD_Funded_Amount = df[df['month_num'] == PMTD_Month]['loan_amount'].sum()
Total_Funded_Amount_MoM_Growth = round(((Total_MTD_Funded_Amount - Total_PMTD_Funded_Amount)/Total_PMTD_Funded_Amount)*100, 2)

In [14]:
print(f'Total Funded Amount: {format_currency(Total_Funded_Amount)}')
print(f'Total MTD Funded Amount: {format_currency(Total_MTD_Funded_Amount)}')
print(f'Total PMTD Funded Amount: {format_currency(Total_PMTD_Funded_Amount)}')
print(f'Total Funded Amount MoM Growth: {format_pct(Total_Funded_Amount_MoM_Growth)}')

Total Funded Amount: Rs.435,757,075.00
Total MTD Funded Amount: Rs.53,981,425.00
Total PMTD Funded Amount: Rs.47,754,825.00
Total Funded Amount MoM Growth: 13.04%

# Total Amount Received

In [15]:
Total_Amount_Received = df['total_payment'].sum()
Total_MTD_Amount_Received = df[df['month_num'] == MTD_Month]['total_payment'].sum()
Total_PMTD_Amount_Received = df[df['month_num'] == PMTD_Month]['total_payment'].sum()
Total_Amount_Received_MoM_Growth = round((((Total_MTD_Amount_Received - Total_PMTD_Amount_Received)/Total_PMTD_Amount_Received)*100), 2)

In [16]:
print(f'Total Funded Applications: {format_currency(Total_Amount_Received)}')
print(f'Total MTD Funded Applications: {format_currency(Total_MTD_Amount_Received)}')
print(f'Total PMTD Funded Applications: {format_currency(Total_PMTD_Amount_Received)}')
print(f'Total Amount Received MoM Growth: {format_pct(Total_Amount_Received_MoM_Growth)} ')

Total Funded Applications: Rs.473,070,933.00
Total MTD Funded Applications: Rs.58,074,380.00
Total PMTD Funded Applications: Rs.50,132,030.00
Total Amount Received MoM Growth: 15.84%

# Average Interest Rate

In [17]:
Average_Int_Rate = df['int_rate'].mean()
Average_MTD_Int_Rate = df[df['month_num'] == MTD_Month]['int_rate'].mean()
Average_PMTD_Int_Rate = df[df['month_num'] == PMTD_Month]['int_rate'].mean()
Average_Int_Rate_MoM_Growth = round(((Average_MTD_Int_Rate - Average_PMTD_Int_Rate)/Average_PMTD_Int_Rate)*100, 2)

In [18]:
print(f'Total Interest Rate: {format_pct(Average_Int_Rate * 100)}')
print(f'Total MTD Interest Rate: {format_pct(Average_MTD_Int_Rate* 100)}')
print(f'Total PMTD Interest Rate: {format_pct(Average_PMTD_Int_Rate* 100)}')
print(f'Average Interest Rate MoM Growth: {format_pct(Average_Int_Rate_MoM_Growth)}')

Total Interest Rate: 12.05%
Total MTD Interest Rate: 12.36%
Total PMTD Interest Rate: 11.94%
Average Interest Rate MoM Growth: 3.47%

# Average Debt to Interest

In [19]:
Average_DTI = df['dti'].mean()
Average_MTD_DTI = df[df['month_num'] == MTD_Month]['dti'].mean()
Average_PMTD_DTI = df[df['month_num'] == PMTD_Month]['dti'].mean()
Average_DTI_MoM_Growth = round(((Average_MTD_Int_Rate - Average_PMTD_Int_Rate)/Average_PMTD_Int_Rate)*100, 2)

In [20]:
print(f'Total Debt to Interest: {format_pct(Average_DTI * 100)}')
print(f'Total MTD Debt to Interest: {format_pct(Average_MTD_DTI* 100)}')
print(f'Total PMTD Debt to Interest: {format_pct(Average_PMTD_DTI* 100)}')
print(f'Average Debt to Interest MoM Growth: {format_pct(Average_DTI_MoM_Growth)}')

Total Debt to Interest: 13.33%
Total MTD Debt to Interest: 13.67%
Total PMTD Debt to Interest: 13.30%
Average Debt to Interest MoM Growth: 3.47%

# Good Loan vs. Bad Loan

In [21]:
Good_Loan = ['Fully Paid', 'Current']
Bad_Loan = ['Charged Off']

## Separating Good Loan and Bad Loan Data

In [22]:
Good_Loan_df = df[df['loan_status'].isin(Good_Loan)]
Bad_Loan_df = df[df['loan_status'].isin(Bad_Loan)]
total_count = df['id'].count()

### Good Loan KPIs

In [23]:
good_loan_pct = round((len(Good_Loan_df)/total_count)*100, 2)
good_loan_applications = Good_Loan_df['id'].count()
good_loan_funded_amount = Good_Loan_df['loan_amount'].sum()
good_loan_total_received_amount = Good_Loan_df['total_payment'].sum()

In [24]:
print(f'Good Loan Applicants Percentage: {format_pct(good_loan_pct)}')
print(f'Total Good Loan Applications: {good_loan_applications}')
print(f'Total Good Loan Funded Amount: {good_loan_funded_amount}')
print(f'Good Loan Total Received Amount: {format_currency(good_loan_total_received_amount)}')

Good Loan Applicants Percentage: 86.18%
Total Good Loan Applications: 33243
Total Good Loan Funded Amount: 370224850
Good Loan Total Received Amount: Rs.435,786,170.00

### Bad Loan KPIs

In [25]:
bad_loan_pct = round((len(Bad_Loan_df)/total_count)*100, 2)
bad_loan_applications = Bad_Loan_df['id'].count()
bad_loan_funded_amount = Bad_Loan_df['loan_amount'].sum()
bad_loan_total_received_amount = Bad_Loan_df['total_payment'].sum()

In [26]:
print(f'Bad Loan Applicants Percentage: {format_pct(bad_loan_pct)}')
print(f'Total Bad Loan Applications: {bad_loan_applications}')
print(f'Total Bad Loan Funded Amount: {bad_loan_funded_amount}')
print(f'Bad Loan Total Received Amount: {format_currency(bad_loan_total_received_amount)}')

Bad Loan Applicants Percentage: 13.82%
Total Bad Loan Applications: 5333
Total Bad Loan Funded Amount: 65532225
Bad Loan Total Received Amount: Rs.37,284,763.00

### Loan Status Grid View

In [27]:
loan_status_grid_view = df.groupby('loan_status').agg(
    Total_Loan_Applications = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Amount_Received = ('total_payment', 'sum'),
    Average_Interest_Rate = ('int_rate', 'mean'),
    Average_DTI = ('dti', 'mean')
).reset_index()

In [28]:
columns = ['Total_Funded_Amount', 'Total_Amount_Received']
for col in columns:
    loan_status_grid_view[col] = loan_status_grid_view[col].apply(format_currency)

In [29]:
pct_columns = ['Average_Interest_Rate', 'Average_DTI']
for p_col in pct_columns:
    loan_status_grid_view[p_col] = loan_status_grid_view[p_col].apply(format_pct)

In [30]:
loan_status_grid_view

,loan_status,Total_Loan_Applications,Total_Funded_Amount,Total_Amount_Received,Average_Interest_Rate,Average_DTI
0,Charged Off,5333,"Rs.65,532,225.00","Rs.37,284,763.00",13.88%,14.00%
1,Current,1098,"Rs.18,866,500.00","Rs.24,199,914.00",15.10%,14.72%
2,Fully Paid,32145,"Rs.351,358,350.00","Rs.411,586,256.00",11.64%,13.17%

# Function to Change Format for Analysis

In [57]:
def change_format(dataframe, *args):
    for data in args:
        dataframe[data] = dataframe[data].apply(format_currency)

## Monthly Trends by Issue Date

In [58]:
monthly_detail = df.groupby('month_name').agg(
    Monthly_Total_Loan_Applications = ('id', 'count'),
    Monthly_Total_Funded_Amount = ('loan_amount', 'sum'),
    Monthly_Total_Amount_Received = ('total_payment', 'sum')
).reset_index().sort_values(ascending=False, by='Monthly_Total_Loan_Applications')

change_format(monthly_detail, 'Monthly_Total_Funded_Amount', 'Monthly_Total_Amount_Received')
monthly_detail

,month_name,Monthly_Total_Loan_Applications,Monthly_Total_Funded_Amount,Monthly_Total_Amount_Received
2,December,4314,"Rs.53,981,425.00","Rs.58,074,380.00"
9,November,4035,"Rs.47,754,825.00","Rs.50,132,030.00"
10,October,3796,"Rs.44,893,800.00","Rs.49,399,567.00"
11,September,3536,"Rs.40,907,725.00","Rs.43,983,948.00"
1,August,3441,"Rs.38,149,600.00","Rs.42,682,218.00"
5,July,3366,"Rs.35,813,900.00","Rs.38,827,220.00"
6,June,3184,"Rs.34,161,475.00","Rs.36,164,533.00"
8,May,2911,"Rs.31,738,350.00","Rs.33,750,523.00"
0,April,2755,"Rs.29,800,800.00","Rs.32,495,533.00"
7,March,2627,"Rs.28,875,700.00","Rs.32,264,400.00"
4,January,2332,"Rs.25,031,650.00","Rs.27,578,836.00"
3,February,2279,"Rs.24,647,825.00","Rs.27,717,745.00"

## Regional Analysis by State

In [59]:
region_detail = df.groupby('address_state').agg(
    Regional_Total_Loan_Applications = ('id', 'count'),
    Regional_Total_Funded_Amount = ('loan_amount', 'sum'),
    Regional_Total_Amount_Received = ('total_payment', 'sum')
).reset_index().sort_values(ascending=False, by='Regional_Total_Loan_Applications')

change_format(region_detail, 'Regional_Total_Funded_Amount', 'Regional_Total_Amount_Received')
region_detail

,address_state,Regional_Total_Loan_Applications,Regional_Total_Funded_Amount,Regional_Total_Amount_Received
4,CA,6894,"Rs.78,484,125.00","Rs.83,901,234.00"
33,NY,3701,"Rs.42,077,050.00","Rs.46,108,181.00"
9,FL,2773,"Rs.30,046,125.00","Rs.31,601,905.00"
42,TX,2664,"Rs.31,236,650.00","Rs.34,392,715.00"
30,NJ,1822,"Rs.21,657,475.00","Rs.23,425,159.00"
14,IL,1486,"Rs.17,124,225.00","Rs.18,875,941.00"
37,PA,1482,"Rs.15,826,525.00","Rs.17,462,908.00"
44,VA,1375,"Rs.15,982,650.00","Rs.17,711,443.00"
10,GA,1355,"Rs.15,480,325.00","Rs.16,728,040.00"
19,MA,1310,"Rs.15,051,000.00","Rs.16,676,279.00"
34,OH,1188,"Rs.12,991,375.00","Rs.14,330,148.00"
20,MD,1027,"Rs.11,911,400.00","Rs.12,985,170.00"
3,AZ,833,"Rs.9,206,000.00","Rs.10,041,986.00"
46,WA,805,"Rs.8,855,525.00","Rs.9,531,739.00"
5,CO,770,"Rs.8,976,000.00","Rs.9,845,810.00"
27,NC,759,"Rs.8,787,575.00","Rs.9,534,813.00"
6,CT,730,"Rs.8,435,575.00","Rs.9,357,612.00"
22,MI,685,"Rs.7,829,900.00","Rs.8,543,660.00"
24,MO,660,"Rs.7,151,175.00","Rs.7,692,732.00"
23,MN,592,"Rs.6,302,600.00","Rs.6,750,746.00"
32,NV,482,"Rs.5,307,375.00","Rs.5,451,443.00"
39,SC,464,"Rs.5,080,475.00","Rs.5,462,458.00"
47,WI,446,"Rs.5,070,450.00","Rs.5,485,161.00"
36,OR,436,"Rs.4,720,150.00","Rs.4,966,903.00"
1,AL,432,"Rs.4,949,225.00","Rs.5,492,272.00"
18,LA,426,"Rs.4,498,900.00","Rs.5,001,160.00"
17,KY,320,"Rs.3,504,100.00","Rs.3,792,530.00"
35,OK,293,"Rs.3,365,725.00","Rs.3,712,649.00"
16,KS,260,"Rs.2,872,325.00","Rs.3,247,394.00"
43,UT,252,"Rs.2,849,225.00","Rs.2,952,412.00"
2,AR,236,"Rs.2,529,700.00","Rs.2,777,875.00"
7,DC,214,"Rs.2,652,350.00","Rs.2,921,854.00"
38,RI,196,"Rs.1,883,025.00","Rs.2,001,774.00"
31,NM,183,"Rs.1,916,775.00","Rs.2,084,485.00"
11,HI,170,"Rs.1,850,525.00","Rs.2,080,184.00"
48,WV,167,"Rs.1,830,525.00","Rs.1,991,936.00"
29,NH,161,"Rs.1,917,900.00","Rs.2,101,386.00"
8,DE,110,"Rs.1,138,100.00","Rs.1,269,136.00"
26,MT,79,"Rs.829,525.00","Rs.892,047.00"
49,WY,79,"Rs.890,750.00","Rs.1,046,050.00"
0,AK,78,"Rs.1,031,800.00","Rs.1,108,570.00"
40,SD,63,"Rs.606,150.00","Rs.656,514.00"
45,VT,54,"Rs.504,100.00","Rs.534,973.00"
25,MS,19,"Rs.139,125.00","Rs.149,342.00"
41,TN,17,"Rs.162,175.00","Rs.141,522.00"
15,IN,9,"Rs.86,225.00","Rs.85,521.00"
13,ID,6,"Rs.59,750.00","Rs.65,329.00"
28,NE,5,"Rs.31,700.00","Rs.24,542.00"
12,IA,5,"Rs.56,450.00","Rs.64,482.00"
21,ME,3,"Rs.9,200.00","Rs.10,808.00"

## Loan Term Analysis

In [56]:
term_detail = df.groupby('term').agg(
    Term_Total_Loan_Applications = ('id', 'count'),
    Term_Total_Funded_Amount = ('loan_amount', 'sum'),
    Term_Total_Amount_Received = ('total_payment', 'sum')
).reset_index().sort_values(ascending=False, by='Term_Total_Loan_Applications')

change_format(term_detail, 'Term_Total_Funded_Amount', 'Term_Total_Amount_Received')
term_detail

,term,Term_Total_Loan_Applications,Term_Total_Funded_Amount,Term_Total_Amount_Received
0,36 months,28237,"Rs.273,041,225.00","Rs.294,709,458.00"
1,60 months,10339,"Rs.162,715,850.00","Rs.178,361,475.00"