In [2]:

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import silhouette_score

In [25]:
df=pd.read_csv('Mall_Customers.csv')
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [27]:
sns.boxplot(df[['Age',	'Annual Income (k$)','Spending Score (1-100)']])
plt.close()

In [30]:
le = LabelEncoder()

In [32]:
df['Gender_Id']=le.fit_transform(df['Gender']) #To inverse it after deleting use inverse_transform()
df

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Gender_Id
0,1,Male,19,15,39,1
1,2,Male,21,15,81,1
2,3,Female,20,16,6,0
3,4,Female,23,16,77,0
4,5,Female,31,17,40,0
...,...,...,...,...,...,...
195,196,Female,35,120,79,0
196,197,Female,45,126,28,0
197,198,Male,32,126,74,1
198,199,Male,32,137,18,1
199,200,Male,30,137,83,1

In [34]:
df= df.drop(columns='Gender')

In [36]:
df['Gender']= le.inverse_transform(df['Gender_Id'])

In [38]:
df

,CustomerID,Age,Annual Income (k$),Spending Score (1-100),Gender_Id,Gender
0,1,19,15,39,1,Male
1,2,21,15,81,1,Male
2,3,20,16,6,0,Female
3,4,23,16,77,0,Female
4,5,31,17,40,0,Female
...,...,...,...,...,...,...
195,196,35,120,79,0,Female
196,197,45,126,28,0,Female
197,198,32,126,74,1,Male
198,199,32,137,18,1,Male
199,200,30,137,83,1,Male