### KNN

In [ ]:
'''
K- Nearest Neighbors
--------------------------
-> Does both classification and regression tasks
->Lazy Algorithm 

Formula
-----------------------
-> Euclidian Distance(root(x2-x1)2 + (y2-y1)2)'''

In [ ]:
#What to find? 
''' -> Optimal number of k (neighbor)
k = 3
'''

In [2]:
import pandas as pd
import numpy as np 
import matplotlib as plt
import seaborn as sns

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
df = pd.read_csv('student.csv')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,higher education,higher education,at_home,teacher,...,very good,medium,high,very low,very low,good,6,5,6,6
1,GP,F,17,U,GT3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,excellent,medium,medium,very low,very low,good,4,5,5,6
2,GP,F,15,U,LE3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,very good,medium,low,low,medium,good,10,7,8,10
3,GP,F,15,U,GT3,T,higher education,5th to 9th grade,health,services,...,good,low,low,very low,very low,excellent,2,15,14,15
4,GP,F,16,U,GT3,T,secondary education,secondary education,other,other,...,very good,medium,low,very low,low,excellent,4,6,10,10

In [17]:
df['G3'].sort_values(ascending= True).unique()

array([ 0,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20], dtype=int64)

In [21]:
def convertMarks(marks):
    if marks >=17 and marks <= 20: 
        return 'A'
    elif marks >= 13 and marks<17:
        return 'B'
    elif marks >= 8 and marks<13:
        return 'C'
    elif marks >= 0 and marks<8:
        return 'Fail' 
    else:
        return 'Invalid Marks to grade'

In [29]:
df['Grade']= df['G3'].apply(convertMarks)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Grade,Grade
0,GP,F,18,U,GT3,A,higher education,higher education,at_home,teacher,...,high,very low,very low,good,6,5,6,6,Fail,Fail
1,GP,F,17,U,GT3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,medium,very low,very low,good,4,5,5,6,Fail,Fail
2,GP,F,15,U,LE3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,low,low,medium,good,10,7,8,10,C,C
3,GP,F,15,U,GT3,T,higher education,5th to 9th grade,health,services,...,low,very low,very low,excellent,2,15,14,15,B,B
4,GP,F,16,U,GT3,T,secondary education,secondary education,other,other,...,low,very low,low,excellent,4,6,10,10,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,5th to 9th grade,5th to 9th grade,services,services,...,high,high,very high,very good,11,9,9,9,C,C
391,MS,M,17,U,LE3,T,secondary education,primary education (4th grade),services,services,...,very high,medium,high,bad,3,14,16,16,B,B
392,MS,M,21,R,GT3,T,primary education (4th grade),primary education (4th grade),other,other,...,medium,medium,medium,good,3,10,8,7,Fail,Fail
393,MS,M,18,R,LE3,T,secondary education,5th to 9th grade,services,other,...,very low,medium,high,excellent,0,11,12,10,C,C
394,MS,M,19,U,LE3,T,primary education (4th grade),primary education (4th grade),other,at_home,...,medium,medium,medium,excellent,5,8,9,9,C,C

In [31]:
df['Grade'].value_counts()

Grade
C       194
B       107
Fail     70
A        24
Name: count, dtype: int64